
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  uri: process.env.Graphql_Source ?? "",
  cache: new InMemoryCache()
})

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body>
      <ApolloProvider client={client}>
        <AntdRegistry>{children}</AntdRegistry>
      </ApolloProvider>
    </body>
  </html>
);
export default RootLayout;
